services:
  metasploitable2:
    image: tleemcjr/metasploitable2
    container_name: metasploitable2
    command: sh -c "/bin/services.sh && tail -f /dev/null"
    networks:
      lan:
        ipv4_address: 10.0.220.12

networks:
  lan:
    driver: macvlan
    driver_opts:
      parent: eth0 # VM’s access port
    ipam:
      config:
        - subnet: 10.0.220.0/24
          gateway: 10.0.220.1